apiVersion: batch/v1
kind: Job
metadata:
  name: helloworld-3
  labels:
    app.name: postgresql
spec:
  template: #template will be use for creating pod
    spec:
      containers:
        - name: busybox #name of the container 
          image: busybox
          command: ["echo","k8s"]  
      restartPolicy: Never
  ttlSecondsAfterFinished: 864000
